package com.igormaznitsa.zxpspritecorrector.exprt;

import com.igormaznitsa.zxpspritecorrector.components.EditorComponent;
import com.igormaznitsa.zxpspritecorrector.HobetaContainer;
import com.igormaznitsa.zxpspritecorrector.utils.Util;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrator
 */
public class ExportHobetaDialog extends javax.swing.JDialog
{
    protected EditorComponent p_Editor;

    protected static final int [] CPUCOLORSTABLE = new int[]
    {
        //Y R G B
        0x0,//new Color(0, 0, 0), // Black
        0x1, //new Color(0, 0, 190), // Blue
        0x4,//new Color(190, 0, 0), // Red
        0x5,//new Color(190, 0, 190),
        0x2,//new Color(0, 190, 0), // Green
        0x3,//new Color(0, 190, 190),
        0x6,//new Color(190, 190, 0),
        0x7,//new Color(190, 190, 190),
        // high bright
        0x8,//new Color(0, 0, 0),
        0x9,//new Color(0, 0, 255),
        0xC,//new Color(255, 0, 0),
        0xD,//new Color(255, 0, 255),
        0xA,//new Color(0, 255, 0),
        0xB,//new Color(0, 255, 255),
        0xE,//new Color(255, 255, 0),
        0xF//new Color(255, 255, 255)
    };
    
    /** Creates new form ExportHobetaDialog
     * @param parent
     * @param _editor 
     */
    public ExportHobetaDialog(java.awt.Frame parent, EditorComponent _editor)
    {
        super(parent, true);
        initComponents();

        p_Editor = _editor;

        HobetaContainer p_hobeta = _editor.getHobetaContainer();

        String s_name = p_hobeta.getName().replace(' ','_');
        String s_fname = s_name;
        
        if (s_name.length()>6) 
        {
            s_fname = s_name.substring(0,5);
        }
        
        char ch_type = p_hobeta.getType();

        p_TextField_FileNameCPU0.setText(s_fname + "C0.$" + ch_type);
        p_TextField_FileNameCPU1.setText(s_fname + "C1.$" + ch_type);
        p_TextField_FileNameCPU2.setText(s_fname + "C2.$" + ch_type);
        p_TextField_FileNameCPU3.setText(s_fname + "C3.$" + ch_type);

        char[] ach_trdos = s_name.toCharArray();
        ach_trdos[7] = '0';
        p_TextField_TRDOSNameCPU0.setText(new String(ach_trdos) + ch_type);
        ach_trdos[7] = '1';
        p_TextField_TRDOSNameCPU1.setText(new String(ach_trdos) + ch_type);
        ach_trdos[7] = '2';
        p_TextField_TRDOSNameCPU2.setText(new String(ach_trdos) + ch_type);
        ach_trdos[7] = '3';
        p_TextField_TRDOSNameCPU3.setText(new String(ach_trdos) + ch_type);

        Dimension p_dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((p_dim.width-getWidth())/2,(p_dim.height-getHeight())/2);
        
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    label1 = new java.awt.Label();
    p_TextField_FileNameCPU0 = new javax.swing.JTextField();
    label2 = new java.awt.Label();
    p_TextField_TRDOSNameCPU0 = new javax.swing.JFormattedTextField();
    jPanel2 = new javax.swing.JPanel();
    label3 = new java.awt.Label();
    p_TextField_FileNameCPU1 = new javax.swing.JTextField();
    label4 = new java.awt.Label();
    p_TextField_TRDOSNameCPU1 = new javax.swing.JFormattedTextField();
    jPanel3 = new javax.swing.JPanel();
    label5 = new java.awt.Label();
    p_TextField_FileNameCPU2 = new javax.swing.JTextField();
    label6 = new java.awt.Label();
    p_TextField_TRDOSNameCPU2 = new javax.swing.JFormattedTextField();
    jPanel4 = new javax.swing.JPanel();
    label7 = new java.awt.Label();
    p_TextField_FileNameCPU3 = new javax.swing.JTextField();
    label8 = new java.awt.Label();
    p_TextField_TRDOSNameCPU3 = new javax.swing.JFormattedTextField();
    p_Button_Ok = new javax.swing.JButton();
    p_Button_Cancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Export color data as separated Hobeta files");
    setResizable(false);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("File for CPU0"));

    label1.setText("File name:");

    label2.setText("TR-Dos name:");

    try {
      p_TextField_TRDOSNameCPU0.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_FileNameCPU0, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22)
        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_TRDOSNameCPU0, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_FileNameCPU0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_TRDOSNameCPU0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("File for CPU1"));

    label3.setText("File name:");

    label4.setText("TR-Dos name:");

    try {
      p_TextField_TRDOSNameCPU1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_FileNameCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_TRDOSNameCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_FileNameCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_TRDOSNameCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("File for CPU2"));

    label5.setText("File name:");

    label6.setText("TR-Dos name:");

    try {
      p_TextField_TRDOSNameCPU2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_FileNameCPU2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(21, 21, 21)
        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_TRDOSNameCPU2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_FileNameCPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_TRDOSNameCPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("File for CPU3"));

    label7.setText("File name:");

    label8.setText("TR-Dos name:");

    try {
      p_TextField_TRDOSNameCPU3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_FileNameCPU3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22)
        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(p_TextField_TRDOSNameCPU3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_FileNameCPU3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(p_TextField_TRDOSNameCPU3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    p_Button_Ok.setText("Ok");
    p_Button_Ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        p_Button_OkActionPerformed(evt);
      }
    });

    p_Button_Cancel.setText("Cancel");
    p_Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        p_Button_CancelActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(p_Button_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(p_Button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {p_Button_Cancel, p_Button_Ok});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(p_Button_Ok)
          .addComponent(p_Button_Cancel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


    private void p_Button_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_Button_OkActionPerformed

        String[] as_fileNames = new String[4];
        String[] as_TrdosNames = new String[4];

        as_fileNames[0] = p_TextField_FileNameCPU0.getText().trim();
        as_fileNames[1] = p_TextField_FileNameCPU1.getText().trim();
        as_fileNames[2] = p_TextField_FileNameCPU2.getText().trim();
        as_fileNames[3] = p_TextField_FileNameCPU3.getText().trim();

        as_TrdosNames[0] = p_TextField_TRDOSNameCPU0.getText().trim();
        as_TrdosNames[1] = p_TextField_TRDOSNameCPU1.getText().trim();
        as_TrdosNames[2] = p_TextField_TRDOSNameCPU2.getText().trim();
        as_TrdosNames[3] = p_TextField_TRDOSNameCPU3.getText().trim();

        JFileChooser p_choser = new JFileChooser();
        p_choser.setDialogTitle("Select a catalog for export");
        p_choser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (p_choser.showDialog(this, "Save") == JFileChooser.APPROVE_OPTION)
        {
            File p_dir = p_choser.getSelectedFile();

            for (int li = 0; li < 4; li++)
            {
                String s_fileName = as_fileNames[li];
                String s_trdosName = as_TrdosNames[li];

                File p_file = new File(p_dir, s_fileName);
                if (p_file.exists())
                {
                    if (JOptionPane.showConfirmDialog(this, "File " + s_fileName + " exists. Overwrite?", "File exists", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION)
                    {
                        continue;
                    }
                }

                FileOutputStream p_outs = null;
                try
                {
                    byte[] ab_hobetaHeader = makeHobetaHeaderBasedOnContainer(p_Editor.getHobetaContainer(), s_trdosName);
                    byte[] ab_data = Util.makeDataForCPU(p_Editor, li);

                    p_outs = new FileOutputStream(p_file);
                    
                    p_outs.write(ab_hobetaHeader);
                    p_outs.write(ab_data);
                    p_outs.flush();
                }
                catch (Throwable _thr)
                {
                    _thr.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Can't save file " + s_fileName + "[" + _thr.getMessage() + "]", "Error", JOptionPane.ERROR_MESSAGE);
                }
                finally
                {
                    if (p_outs != null)
                    {
                        try
                        {
                            p_outs.close();
                        }
                        catch (Throwable _thr)
                        {
                        }
                    }
                }
            }
        }
        else
        {
            return;
        }

        dispose();
    }//GEN-LAST:event_p_Button_OkActionPerformed

    private byte[] makeHobetaHeaderBasedOnContainer(HobetaContainer _container, String _trdosName) throws IOException
    {
        ByteArrayOutputStream p_out = new ByteArrayOutputStream(15);

        int i_acc = 0;

        // name

        for (int li = 0; li < 9; li++)
        {
            if (_trdosName.length() <= li)
            {
                p_out.write((byte) ' ');
                i_acc += ' ';
            }
            else
            {
                char ch_ch = _trdosName.charAt(li);
                p_out.write((byte) ch_ch);
                i_acc += ch_ch;
            }
        }

        // start
        int i_val = _container.getStart();
        p_out.write(i_val & 0xFF);
        p_out.write(i_val >>> 8);

        i_acc += ((i_val & 0xFF) + (i_val >>> 8));

        // length
        i_val = _container.getLength();
        p_out.write(i_val & 0xFF);
        p_out.write(i_val >>> 8);
        i_acc += ((i_val & 0xFF) + (i_val >>> 8));

        // Sectors
        i_val = _container.getSectors();
        p_out.write(i_val >>> 8);
        p_out.write(i_val & 0xFF);
        i_acc += ((i_val & 0xFF) + (i_val >>> 8));

        // crc
        i_acc *= 257;
        i_acc += 105;
        i_acc &= 0xFFFF;

        p_out.write(i_acc & 0xFF);
        p_out.write(i_acc >>> 8);

        p_out.flush();

        return p_out.toByteArray();
    }

    private void p_Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_Button_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_p_Button_CancelActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private java.awt.Label label1;
  private java.awt.Label label2;
  private java.awt.Label label3;
  private java.awt.Label label4;
  private java.awt.Label label5;
  private java.awt.Label label6;
  private java.awt.Label label7;
  private java.awt.Label label8;
  private javax.swing.JButton p_Button_Cancel;
  private javax.swing.JButton p_Button_Ok;
  private javax.swing.JTextField p_TextField_FileNameCPU0;
  private javax.swing.JTextField p_TextField_FileNameCPU1;
  private javax.swing.JTextField p_TextField_FileNameCPU2;
  private javax.swing.JTextField p_TextField_FileNameCPU3;
  private javax.swing.JFormattedTextField p_TextField_TRDOSNameCPU0;
  private javax.swing.JFormattedTextField p_TextField_TRDOSNameCPU1;
  private javax.swing.JFormattedTextField p_TextField_TRDOSNameCPU2;
  private javax.swing.JFormattedTextField p_TextField_TRDOSNameCPU3;
  // End of variables declaration//GEN-END:variables
}
