#!/bin/sh
JAVA_FLAGS="-XX:+UseZGC -XX:+TieredCompilation -XX:MaxMetaspaceSize=128m -Dsun.rmi.transport.tcp.maxConnectionThreads=0 -XX:-DontCompileHugeMethods -XX:+DisableAttachMechanism -Xms512m -Xmx1024m --add-opens=java.base/java.util=ALL-UNNAMED --enable-native-access=ALL-UNNAMED"
JAVA_RUN="$APPDIR/jre/bin/java"
JAVA_LOG_CONFIG="$APPDIR/logger.properties"

for jar in "$APPDIR"/zxpoly-emul-*.jar; do
  if [ -f "$jar" ]; then
    exec "$JAVA_RUN" $JAVA_FLAGS $JAVA_EXTRA_GFX_FLAGS "-Djava.util.logging.config.file=$JAVA_LOG_CONFIG" -jar "$jar" "$@"
  fi
done

echo "zxpoly-emul jar not found in $APPDIR" >&2
exit 1
