#!/bin/sh
BASEDIR=`dirname "$0"`

exec "$BASEDIR"/jre/bin/java -Dsun.rmi.transport.tcp.maxConnectionThreads=0 -XX:-DontCompileHugeMethods -XX:+DisableAttachMechanism -Djava.library.path="$BASEDIR" -Xdock:icon="$BASEDIR"/../Resources/appico.png  -jar "$BASEDIR"/zxpoly-emul*.jar
