package com.igormaznitsa.zxpspritecorrector;

import com.igormaznitsa.zxpspritecorrector.components.EditorComponent;
import com.igormaznitsa.zxpspritecorrector.utils.Util;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class ExportTAPDialog extends javax.swing.JDialog
{

    protected static File p_LastFile;
    protected EditorComponent p_Editor;

    /** Creates new form ExportTAPDialog */
    public ExportTAPDialog(java.awt.Frame parent, EditorComponent _editor)
    {
        super(parent, true);
        initComponents();

        p_Editor = _editor;

        HobetaContainer p_container = _editor.getHobetaContainer();
        String s_name = p_container.getName().trim();

        p_Field_TapFileName.setText((s_name.isEmpty() ? "tapfile" : s_name)+".tap");

        if (s_name.length()>8) s_name = s_name.substring(0,8);

        p_Field_CPU0Name.setText(s_name+"_0");
        p_Field_CPU1Name.setText(s_name+"_1");
        p_Field_CPU2Name.setText(s_name+"_2");
        p_Field_CPU3Name.setText(s_name+"_3");

        Dimension p_scrSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((p_scrSize.width - getWidth()) / 2, (p_scrSize.height - getHeight()) / 2);

        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    p_Button_Cancel = new javax.swing.JButton();
    p_Button_Ok = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    p_Field_CPU0Name = new javax.swing.JFormattedTextField();
    p_Field_CPU1Name = new javax.swing.JFormattedTextField();
    p_Field_CPU2Name = new javax.swing.JFormattedTextField();
    p_Field_CPU3Name = new javax.swing.JFormattedTextField();
    p_Field_TapFileName = new javax.swing.JFormattedTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Export data as a TAP file");

    p_Button_Cancel.setText("Cancel");
    p_Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        p_Button_CancelActionPerformed(evt);
      }
    });

    p_Button_Ok.setText("Ok");
    p_Button_Ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        p_Button_OkActionPerformed(evt);
      }
    });

    jLabel1.setText("TAP name:");

    jLabel2.setText("CPU0 file name:");

    jLabel3.setText("CPU1 file name:");

    jLabel4.setText("CPU2 file name:");

    jLabel5.setText("CPU3 file name:");

    try {
      p_Field_CPU0Name.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    try {
      p_Field_CPU1Name.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    try {
      p_Field_CPU2Name.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    try {
      p_Field_CPU3Name.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?*********")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    try {
      p_Field_TapFileName.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?******************************")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(p_Button_Ok)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(p_Button_Cancel))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(p_Field_TapFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(p_Field_CPU0Name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(p_Field_CPU1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(p_Field_CPU2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(p_Field_CPU3Name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {p_Button_Cancel, p_Button_Ok});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(p_Field_TapFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(p_Field_CPU0Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(p_Field_CPU1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(p_Field_CPU2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(p_Field_CPU3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(p_Button_Cancel)
          .addComponent(p_Button_Ok))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void p_Button_OkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_p_Button_OkActionPerformed
    {//GEN-HEADEREND:event_p_Button_OkActionPerformed
        try
        {
            JFileChooser p_fileChooser = new JFileChooser(p_LastFile);

            String s_name = p_Field_TapFileName.getText().trim();
            if (!s_name.toLowerCase().endsWith(".tap"))
            {
                s_name += ".tap";
            }

            p_fileChooser.setDialogTitle("Select directory to save the TAP file ");
            p_fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);

            p_fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            p_fileChooser.setMultiSelectionEnabled(false);

            final String[] as_nameFiles = new String[]
            {
                p_Field_CPU0Name.getText(), p_Field_CPU1Name.getText(), p_Field_CPU2Name.getText(), p_Field_CPU3Name.getText()
            };

            if (p_fileChooser.showDialog(this, "Save") == JFileChooser.APPROVE_OPTION)
            {
                p_LastFile = p_fileChooser.getSelectedFile();

                ByteArrayOutputStream p_buffer = new ByteArrayOutputStream(160000);
                DataOutputStream p_dataStream = new DataOutputStream(p_buffer);

                HobetaContainer p_container = p_Editor.getHobetaContainer();

                for (int li = 3; li >=0; li--)
                {
                    String s_fileName = as_nameFiles[li];

                    p_container.saveAsTapHeader(p_dataStream, s_fileName);
                    p_container.saveAsTapBlock(p_dataStream, Util.makeDataForCPU(p_Editor, li));
                }

                p_dataStream.flush();

                byte [] ab_tapData = p_buffer.toByteArray();

                File p_file = new File(p_LastFile,s_name);
                FileOutputStream p_outStream = new FileOutputStream(p_file);
                try
                {
                    p_outStream.write(ab_tapData);
                    p_outStream.flush();
                }
                finally
                {
                    try
                    {
                        p_outStream.close();
                    }
                    catch(Throwable _thr){}
                }

                dispose();
            }
        }
        catch (Throwable _thr)
        {
            _thr.printStackTrace();
            JOptionPane.showMessageDialog(this, "Can't create or save ["+_thr.getMessage()+']',"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_p_Button_OkActionPerformed

    private void p_Button_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_p_Button_CancelActionPerformed
    {//GEN-HEADEREND:event_p_Button_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_p_Button_CancelActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JButton p_Button_Cancel;
  private javax.swing.JButton p_Button_Ok;
  private javax.swing.JFormattedTextField p_Field_CPU0Name;
  private javax.swing.JFormattedTextField p_Field_CPU1Name;
  private javax.swing.JFormattedTextField p_Field_CPU2Name;
  private javax.swing.JFormattedTextField p_Field_CPU3Name;
  private javax.swing.JFormattedTextField p_Field_TapFileName;
  // End of variables declaration//GEN-END:variables
}
