package com.igormaznitsa.zxpoly.components;

public interface Timings {
  int CPU_FREQ_HZ = 3546900;

  int PAPER_LINES = 192;

  int TSTATES_PER_LINE = 228;

  int SCREEN_HIDDEN_LINES = 8;
  int LINES_BEFORE_FIRST_PAPER_LINE = 63;
  int LINES_AFTER_PAPER = 56;

  int SCREEN_VISIBLE_LINES_BEFORE_RASTER = LINES_BEFORE_FIRST_PAPER_LINE - SCREEN_HIDDEN_LINES;
  int TOTAL_SCREEN_LINES = LINES_BEFORE_FIRST_PAPER_LINE + LINES_AFTER_PAPER + PAPER_LINES;
  int TOTAL_VISIBLE_SCREEN_LINES = TOTAL_SCREEN_LINES - SCREEN_HIDDEN_LINES;

  int TSTATES_SCREEN_START = SCREEN_HIDDEN_LINES * TSTATES_PER_LINE;
  int TSTATES_RASTER_START = LINES_BEFORE_FIRST_PAPER_LINE * TSTATES_PER_LINE;
  int TSTATES_RASTER_END = TSTATES_RASTER_START + PAPER_LINES * TSTATES_PER_LINE;
  int TSTATES_SCREEN_END = TSTATES_RASTER_END + LINES_AFTER_PAPER * TSTATES_PER_LINE;

  int TSTATES_PER_FRAME = TSTATES_SCREEN_END;

  int TSTATES_INT_NMI_LENGTH = 36;

}
