package com.igormaznitsa.zxpoly.components;

public interface Timings {
  int CPU_FREQ_HZ = 3546900;

  int ROWS_VSYNC = 8;
  int ROWS_RASTER = 192;
  int ROWS_BOTTOM_BORDER = 56;
  int ROWS_TOP_BORDER = 56;

  int TSTATES_H_BLANKING = 48;
  int TSTATES_H_BORDER_LEFT = 26;
  int TSTATES_H_RASTER_DATA = 128;
  int TSTATES_H_BORDER_RIGHT = 26;
  int TSTATES_H_WHOLE_ROW = TSTATES_H_BLANKING + TSTATES_H_BORDER_LEFT + TSTATES_H_RASTER_DATA + TSTATES_H_BORDER_RIGHT;

  int VERT_TSTATES_RASTER_START = 0;

  int VERT_TSTATES_BORDER_BOTTOM_START = VERT_TSTATES_RASTER_START + ROWS_RASTER * TSTATES_H_WHOLE_ROW;
  int VERT_TSTATES_VSYNC = VERT_TSTATES_BORDER_BOTTOM_START + ROWS_BOTTOM_BORDER * TSTATES_H_WHOLE_ROW;
  int VERT_TSTATES_TOP_BORDER = VERT_TSTATES_VSYNC + ROWS_VSYNC * TSTATES_H_WHOLE_ROW;
  int VERT_TSTATES_TOP_BORDER_END = VERT_TSTATES_TOP_BORDER + ROWS_TOP_BORDER * TSTATES_H_WHOLE_ROW;

  int TOTAL_ROWS = VERT_TSTATES_TOP_BORDER_END / TSTATES_H_WHOLE_ROW;
  int TOTAL_VISIBLE_ROWS = TOTAL_ROWS - ROWS_VSYNC;

  int TSTATES_START_BORDER = (ROWS_VSYNC + ROWS_TOP_BORDER) * TSTATES_H_WHOLE_ROW;

  int TSTATES_INT_NMI_LENGTH = 30;

  int TSTATES_FRAME = VERT_TSTATES_TOP_BORDER_END;
}
