#!/bin/bash
echo it needs ZASM 4.0.11 from http://k1.spdns.de/Develop/Projects/zasm-4.0/Distributions/

# slicing images to zxpoly planes

JAVA_EXE=/home/igorm/SDK/jdk-11/bin/java

rm -f $PWD/images/*.ZX*
rm -f $PWD/images/*.c*

$JAVA_EXE -jar $PWD/bin/zxsc.jar sliceImage $PWD/images/256.png
$JAVA_EXE -jar $PWD/bin/zxsc.jar sliceImage $PWD/images/512.png

# packing zxpoly planes to lpz

$PWD/bin/zx0 $PWD/images/256c0.c0 $PWD/images/256C0.ZX0
$PWD/bin/zx0 $PWD/images/256c1.c1 $PWD/images/256C1.ZX0
$PWD/bin/zx0 $PWD/images/256c2.c2 $PWD/images/256C2.ZX0
$PWD/bin/zx0 $PWD/images/256c3.c3 $PWD/images/256C3.ZX0

$PWD/bin/zx0 $PWD/images/512c0.c0 $PWD/images/512C0.ZX0
$PWD/bin/zx0 $PWD/images/512c1.c1 $PWD/images/512C1.ZX0
$PWD/bin/zx0 $PWD/images/512c2.c2 $PWD/images/512C2.ZX0
$PWD/bin/zx0 $PWD/images/512c3.c3 $PWD/images/512C3.ZX0


TARGETROM=$PWD/../zxpoly-emul/src/main/resources/com/igormaznitsa/zxpoly/rom/zxpolytest.prom

$PWD/bin/zasm --z80 -l0 $PWD/zxpolytest.asm -o $TARGETROM

rm -f $PWD/images/*.ZX*
rm -f $PWD/images/*.c*
