#!/bin/bash
echo it needs ZASM 4.0.11 from http://k1.spdns.de/Develop/Projects/zasm-4.0/Distributions/

$PWD/bin/zasm -l0 $PWD/zxpolytest.asm -o $PWD/../zxpoly-emul/src/main/resources/com/igormaznitsa/zxpoly/rom/zxpolytest.rom
