	DEVICE ZXSPECTRUM128

LOADBIN EQU 24500
STARTBIN1 EQU 38913
STARTBIN2 EQU 48800

START	EQU		#4700

	ORG START
	JP MAIN

	INCLUDE "zxpoly.mac"
	INCLUDE "trdos.mac"
	INCLUDE "other.mac"

MAIN
	DI
;	LD A,#30
;	LD BC,#7FFD

	DOS_RESET ; reset TR-DOS
	DOS_DRIVE 0 ; select A drive

	DOS_DISK

	DI

	DOS_LOAD DATA_BIN3,LOADBIN
	DI
	COPY2CPU CPU3,#4000,#FFFF-#4000

	DOS_LOAD DATA_BIN2,LOADBIN
	DI
	COPY2CPU CPU2,#4000,#FFFF-#4000

	DOS_LOAD DATA_BIN1,LOADBIN
	DI
	COPY2CPU CPU1,#4000,#FFFF-#4000

	DOS_LOAD DATA_BIN0,LOADBIN
	DI
	SAVEREGS regarea

	COPY2CPU CPU3,#4000,#1FB3
	COPY2CPU CPU2,#4000,#1FB3
	COPY2CPU CPU1,#4000,#1FB3

	; lock IO writing for CPU1-CPU3
	DISABLE_IO_WR CPU1,1
	DISABLE_IO_WR CPU2,1
	DISABLE_IO_WR CPU3,1

	SETRESCOMMAND CPU0,#C3,RUNCODE & #FF,RUNCODE>>>8
	SETRESCOMMAND CPU1,#C3,RUNCODE & #FF,RUNCODE>>>8
	SETRESCOMMAND CPU2,#C3,RUNCODE & #FF,RUNCODE>>>8
	SETRESCOMMAND CPU3,#C3,RUNCODE & #FF,RUNCODE>>>8

	SETPOLYMAIN #97 ; block+softreset+zxpolyvideohigh

; Here is the common start block for all CPU modules
RUNCODE
	DI
	LD A,#10
	LD BC,#7FFD
	OUT (C),A

	LOADREGS regarea
	BORDER 1
	CALL STARTBIN1
	BORDER 4
	CALL STARTBIN2

; area of registers saving

    BLOCK 40
regarea 


DATA_BIN0	DEFB "tzxun260C"
DATA_BIN1	DEFB "tzxun261C"
DATA_BIN2	DEFB "tzxun262C"
DATA_BIN3	DEFB "tzxun263C"

	EMPTYTRD "target/zxword.trd"
	SAVETRD "target/zxword.trd","ploader.C",START,$-START
